# Generated by Django 5.1.5 on 2025-01-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user_roles',
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], default='USER', max_length=10),
        ),
    ]
