# Generated by Django 5.1.5 on 2025-01-29 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0007_company_users_alter_companyuser_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 28, 17, 19, 28, 151926)),
        ),
        migrations.DeleteModel(
            name='CompanyUser',
        ),
    ]
