# Generated by Django 5.1.5 on 2025-01-30 08:17

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0008_alter_task_due_date_delete_companyuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invited_users',
            field=models.ManyToManyField(related_name='invitedusers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 11, 17, 39, 219365)),
        ),
    ]
