# Generated by Django 5.1.5 on 2025-01-31 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0011_alter_company_invited_users_alter_company_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 2, 11, 45, 40, 209097)),
        ),
    ]
