# Generated by Django 5.1.5 on 2025-02-03 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0016_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 5, 18, 34, 14, 897647)),
        ),
    ]
