# Generated by Django 5.1.5 on 2025-02-03 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0017_notification_company_name_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 5, 19, 46, 43, 49949)),
        ),
    ]
