# Generated by Django 5.1.5 on 2025-02-05 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0020_alter_notification_company_name_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 7, 12, 16, 49, 337123)),
        ),
    ]
