# Generated by Django 5.1.5 on 2025-02-06 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0022_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 6, 30, 54, 356118)),
        ),
    ]
