# Generated by Django 5.1.5 on 2025-02-06 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0025_alter_task_due_date_personal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_account',
            name='tasks',
            field=models.ManyToManyField(related_name='tasks', to='task_management.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 16, 5, 16, 769031)),
        ),
    ]
