# Generated by Django 5.1.5 on 2025-02-06 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0028_category_remove_task_category_task_personal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='personal',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 16, 31, 48, 541756)),
        ),
    ]
