# Generated by Django 5.1.5 on 2025-02-06 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0030_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='company_name',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 17, 38, 58, 455573)),
        ),
    ]
