# Generated by Django 5.1.5 on 2025-02-06 14:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0031_remove_notification_company_name_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 8, 17, 52, 31, 590277)),
        ),
        migrations.AlterField(
            model_name='task',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_tasks', to='task_management.personal_account'),
        ),
    ]
