# Generated by Django 5.1.5 on 2025-02-08 09:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0034_alter_notification_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='task_management.personal_account'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 10, 12, 12, 8, 651759)),
        ),
    ]
