# Generated by Django 5.1.5 on 2025-02-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_model', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='https://shorturl.at/nLEzO', upload_to='prof_pics/'),
        ),
    ]
