# Generated by Django 5.1.5 on 2025-02-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_model', '0005_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='personal',
        ),
    ]
